### ISSUE TITLE
Pasar Issues

### ISSUE THREAD

**Issue by AdCalzadilla** [ULL-ESIT-GRADOII-PL/conversor-de-temperatura-simple-pl_asac#4]
Los issues del repositorio "privado" no se pasan al repositorio de **classroom"

**Comment by alu0100769609** [comment]
Esto es debido a que los issues son locales al repositorio. Aun así, existe un proyecto llamado ["hub"](https://github.com/defunkt/hub) que permite pasar un issue mediante un simple comando en la terminal.

``` bash
$ hub pull-request -i 4
```

Esto utiliza la api de Github y adjunta una solicitud de pull request para la rama actual al issue nº 4 existente

**Comment by AdCalzadilla** [comment]
Muchas gracias! Lo probaré.
